before_script:
  - echo $CI_PROJECT_DIR
  - docker --version
  - docker-compose --version

stages:
  - unittest
  - build
  - ltptest

build_main:
  stage: build
  tags:
    - docker
  script:
    - docker/run_docker.sh -b

unittest:
  stage: unittest
  tags:
    - docker
  script:
    - docker/run_docker.sh -t

ltptest:
  stage: ltptest
  tags:
    - docker
  script:
    - docker/run_docker.sh --clean
    - docker/run_docker.sh -l

