site_name: Container File System

nav:
- Overview: 'overview.md'
- Quick Start Guide: 'user-guide.md'
- Master Administration:
    - 'Cluster': 'admin-api/cluster.md'
    - 'Meta Node': 'admin-api/metanode.md'
    - 'Data Node': 'admin-api/datanode.md'
    - 'Volume': 'admin-api/vol.md'
    - 'Meta Partition': 'admin-api/metapartition.md'
    - 'Data Partition': 'admin-api/datapartition.md'
    - 'Master Management': 'admin-api/master-manage.md'
- MetaNode Administration:
    - 'Partition': 'admin-api/metaNode-partition.md'
    - 'Inode': 'admin-api/metaNode-inode.md'
    - 'Dentry': 'admin-api/metaNode-dentry.md'
- Design: 'design.md'
- Performance: 'performance.md'
- Evaluation: 'evaluation.md'

theme: readthedocs
